-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."chat_group_members" add column "notified_at" timestamptz
--  null;
