-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO "public"."activity_verb" (value, comment) VALUES
--
--     ('deleted', 'deleted');
