-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."user_profile" add column "email_activity" boolean
--  not null default 'true';
