-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."transfer_request" add column "original_owner_id" uuid
--  not null;
